-- MySQL Script generated by MySQL Workbench
-- ven. 29 oct. 2021 14:16:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proxysoluce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proxysoluce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proxysoluce` ;
USE `proxysoluce` ;

-- -----------------------------------------------------
-- Table `proxysoluce`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proxysoluce`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(255) NOT NULL,
  `complement` VARCHAR(255) NULL,
  `cp` INT NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proxysoluce`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proxysoluce`.`person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(100) NOT NULL,
  `lastname` VARCHAR(100) NOT NULL,
  `birth_date` DATE NOT NULL,
  `mail` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `login` VARCHAR(100) NOT NULL,
  `address_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_person_address_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_person_address`
    FOREIGN KEY (`address_id`)
    REFERENCES `proxysoluce`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proxysoluce`.`skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proxysoluce`.`skill` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(300) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proxysoluce`.`doing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proxysoluce`.`doing` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `person_id` INT NULL,
  `skill_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_doing_person1_idx` (`person_id` ASC) VISIBLE,
  INDEX `fk_doing_skill1_idx` (`skill_id` ASC) VISIBLE,
  CONSTRAINT `fk_doing_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `proxysoluce`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doing_skill1`
    FOREIGN KEY (`skill_id`)
    REFERENCES `proxysoluce`.`skill` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proxysoluce`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proxysoluce`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proxysoluce`.`offering`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proxysoluce`.`offering` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(300) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `person_id` INT NULL,
  `category_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_offering_person1_idx` (`person_id` ASC) VISIBLE,
  INDEX `fk_offering_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_offering_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `proxysoluce`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offering_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `proxysoluce`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO skill (name) VALUES ('jardinage'), ('maconnerie'), ('mecanique'), ('menuiserie'), ('montage-meuble'), ('plomberie'), ('electricite'), ('carrelage'), ('carrosserie'), ('electronique'), ('informatique'), ('menage'), ('repassage');
INSERT INTO category (name) VALUES ('service à la personne'), ('bricolage'), ('informatique'), ('catégorie4'), ('catégorie5');

INSERT INTO address (street, cp, city) VALUES ('rue de la République', '69002', 'Lyon');
INSERT INTO person (lastname, firstname, birth_date, mail, password, login, address_id) VALUES ('Gautrais', 'Jérémy', '1990-05-09', 'j.gautrais@compagnies.com', 'Jeremy', 'root', (SELECT id FROM address WHERE Id=(SELECT LAST_INSERT_ID())));

INSERT INTO address (street, cp, city) VALUES ('rue de la République', '69002', 'Oullins');
INSERT INTO person (lastname, firstname, birth_date, mail, password, login, address_id) VALUES ('Verchere', 'Anthony', '1990-05-09', 'anthony@compagnies.com', 'Anthony', 'root', (SELECT id FROM address WHERE Id=(SELECT LAST_INSERT_ID())));

INSERT INTO address (street, cp, city) VALUES ('rue de la République', '69002', 'Grenoble');
INSERT INTO person (lastname, firstname, birth_date, mail, password, login, address_id) VALUES ('Gaudin', 'Valentin', '1990-05-09', 'valentin@compagnies.com', 'Valentin', 'root', (SELECT id FROM address WHERE Id=(SELECT LAST_INSERT_ID())));

INSERT INTO address (street, cp, city) VALUES ('rue de la République', '69002', 'Lyon');
INSERT INTO person (lastname, firstname, birth_date, mail, password, login, address_id) VALUES ('Hoffman', 'Michel', '1990-05-09', 'michel@compagnies.com', 'Michel', 'root', (SELECT id FROM address WHERE Id=(SELECT LAST_INSERT_ID())));

INSERT INTO doing (person_id, skill_id) VALUES ((SELECT id FROM person WHERE name="Gautrais"), (SELECT id FROM skill WHERE name="informatique"));
INSERT INTO doing (person_id, skill_id) VALUES ((SELECT id FROM person WHERE name="Verchere"), (SELECT id FROM skill WHERE name="plomberie"));
INSERT INTO doing (person_id, skill_id) VALUES ((SELECT id FROM person WHERE name="Gaudin"), (SELECT id FROM skill WHERE name="jardinage"));
INSERT INTO doing (person_id, skill_id) VALUES ((SELECT id FROM person WHERE name="Hoffman"), (SELECT id FROM skill WHERE name="electricite"));

INSERT INTO offering (title, city, description, person_id, category_id) VALUES ('Développement de sites web', 'Lyon', 'Je vous propose mes services pour développer des sites web interactifs.', (SELECT id FROM person WHERE name="Gautrais"), (SELECT id FROM category WHERE name="informatique"));
INSERT INTO offering (title, city, description, person_id, category_id) VALUES ('Développement d intranet', 'Lyon', 'Je vous propose mes services pour développer des intranets.', (SELECT id FROM person WHERE name="Hoffman"), (SELECT id FROM category WHERE name="informatique"));

INSERT INTO offering (title, city, description, person_id, category_id) VALUES ('Taille de haie', 'Grenoble', 'Je vous propose mes services pour tailler des haies.', (SELECT id FROM person WHERE name="Gaudin"), (SELECT id FROM category WHERE name="bricolage"));

INSERT INTO offering (title, city, description, person_id, category_id) VALUES ('Repassage', 'Oullins', 'Je vous propose mes services pour repasser le linge.', (SELECT id FROM person WHERE name="Verchere"), (SELECT id FROM category WHERE name="service à la personne"));












