-- MySQL Script generated by MySQL Workbench
-- ven. 29 oct. 2021 14:16:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proxysoluce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proxysoluce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proxysoluce` ;
USE `proxysoluce` ;


-- -----------------------------------------------------
-- Table `proxysoluce`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proxysoluce`.`person` (
  `id` int NOT NULL AUTO_INCREMENT,
  `firstname` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `lastname` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `mail` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `birth` date NOT NULL,
  `user` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `pass` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `adress` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `postal` int NOT NULL,
  `town` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `picture` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proxysoluce`.`skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proxysoluce`.`skill` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(300) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proxysoluce`.`doing`
-- -----------------------------------------------------
CREATE TABLE `user_skill` (
  `person_id` int DEFAULT NULL,
  `skill_id` int DEFAULT NULL,
  KEY `person_id` (`person_id`),
  KEY `skill_id` (`skill_id`),
  CONSTRAINT `user_skill_ibfk_3` FOREIGN KEY (`person_id`) REFERENCES `person` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `user_skill_ibfk_4` FOREIGN KEY (`skill_id`) REFERENCES `skill` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proxysoluce`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proxysoluce`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proxysoluce`.`offering`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proxysoluce`.`offering` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(300) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `person_id` INT NULL,
  `category_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_offering_person1_idx` (`person_id` ASC) VISIBLE,
  INDEX `fk_offering_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_offering_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `proxysoluce`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offering_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `proxysoluce`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO skill (name) VALUES ('jardinage'), ('maconnerie'), ('mecanique'), ('menuiserie'), ('montage-meuble'), ('plomberie'), ('electricite'), ('carrelage'), ('carrosserie'), ('electronique'), ('informatique'), ('menage'), ('repassage');
INSERT INTO category (name) VALUES ('service à la personne'), ('bricolage'), ('informatique'), ('catégorie4'), ('catégorie5');


INSERT INTO person (`firstname` , `lastname`, `mail`, `birth`, `user`,`pass`, `adress`,`postal`, `town`) VALUES ('Jérémy', 'Gautrais', 'j.gautrais@compagnies.com', '1990-05-09', 'jeremy', 'root', '17 rue Claude Jusseaud', '69110', 'Sainte Foy les Lyon');

INSERT INTO person (`firstname` , `lastname`, `mail`, `birth`, `user`,`pass`, `adress`,`postal`, `town`) VALUES ('Valentin', 'Gaudin', 'v.gaudin@compagnies.com', '1990-05-09', 'valentin', 'root', '1rue du Platane', '32000', 'Grenoble');


INSERT INTO offering (title, city, description, person_id, category_id) VALUES ('Développement de sites web', 'Lyon', 'Je vous propose mes services pour développer des sites web interactifs.', (SELECT id FROM person WHERE lastname="Gautrais"), (SELECT id FROM category WHERE name="informatique"));

INSERT INTO offering (title, city, description, person_id, category_id) VALUES ('Taille de haie', 'Grenoble', 'Je vous propose mes services pour tailler des haies.', (SELECT id FROM person WHERE lastname="Gaudin"), (SELECT id FROM category WHERE name="bricolage"));

plomberie, bricolage, demenagement, pose cuisine, jardinage, peinture













